# Generated by Django 5.1.3 on 2024-12-21 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseTrackerApp", "0002_remove_lungcancertrackermodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lungcancertrackermodel",
            name="lung_cancer",
        ),
    ]
