# Generated by Django 5.1.3 on 2024-12-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseTrackerApp", "0003_remove_lungcancertrackermodel_lung_cancer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lungcancertrackermodel",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "Male"), (0, "Female")], max_length=1
            ),
        ),
    ]
