# Generated by Django 5.1.3 on 2024-12-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diseaseTrackerApp", "0004_alter_lungcancertrackermodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lungcancertrackermodel",
            name="gender",
            field=models.IntegerField(choices=[(1, "Male"), (0, "Female")]),
        ),
    ]
